services:
    _defaults:
        autowire: true
        autoconfigure: true

    OHMedia\FormBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaFormBundle.php'
